# Generated by Django 3.1.4 on 2021-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('lastname', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
